# --- !Ups

CREATE TABLE "USER" (
    "ID" BIGSERIAL PRIMARY KEY,
    "EMAIL" VARCHAR(255) NOT NULL
);

CREATE TABLE "LOGIN_INFO" (
    "ID" BIGSERIAL PRIMARY KEY,
    "PROVIDER_ID" VARCHAR(255) NOT NULL,
    "PROVIDER_KEY" VARCHAR(255) NOT NULL
);

CREATE TABLE "USER_LOGIN_INFO" (
    "USER_ID" BIGINT NOT NULL,
    "LOGIN_INFO_ID" BIGINT NOT NULL
);

CREATE TABLE "PASSWORD_INFO" (
    "HASHER" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "SALT" VARCHAR(255),
    "LOGIN_INFO_ID" BIGINT NOT NULL
);

# --- !Downs

DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS "LOGIN_INFO";
DROP TABLE IF EXISTS "USER_LOGIN_INFO";
DROP TABLE IF EXISTS "PASSWORD_INFO";
